/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphsIndexRouteImport } from './routes/graphs/index'
import { Route as GraphsGraphIdRouteImport } from './routes/graphs/$graphId'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org/$orgId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgOrgIdTeamTeamIdGraphsIndexRouteImport } from './routes/org/$orgId/team/$teamId/graphs/index'
import { Route as OrgOrgIdTeamTeamIdGraphsGraphIdRouteImport } from './routes/org/$orgId/team/$teamId/graphs/$graphId'

const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsIndexRoute = GraphsIndexRouteImport.update({
  id: '/graphs/',
  path: '/graphs/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsGraphIdRoute = GraphsGraphIdRouteImport.update({
  id: '/graphs/$graphId',
  path: '/graphs/$graphId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/org/$orgId/',
  path: '/org/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdTeamTeamIdGraphsIndexRoute =
  OrgOrgIdTeamTeamIdGraphsIndexRouteImport.update({
    id: '/org/$orgId/team/$teamId/graphs/',
    path: '/org/$orgId/team/$teamId/graphs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdTeamTeamIdGraphsGraphIdRoute =
  OrgOrgIdTeamTeamIdGraphsGraphIdRouteImport.update({
    id: '/org/$orgId/team/$teamId/graphs/$graphId',
    path: '/org/$orgId/team/$teamId/graphs/$graphId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/graphs/$graphId': typeof GraphsGraphIdRoute
  '/graphs/': typeof GraphsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/graphs/$graphId': typeof OrgOrgIdTeamTeamIdGraphsGraphIdRoute
  '/org/$orgId/team/$teamId/graphs/': typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/graphs/$graphId': typeof GraphsGraphIdRoute
  '/graphs': typeof GraphsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/graphs/$graphId': typeof OrgOrgIdTeamTeamIdGraphsGraphIdRoute
  '/org/$orgId/team/$teamId/graphs': typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/graphs/$graphId': typeof GraphsGraphIdRoute
  '/graphs/': typeof GraphsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/graphs/$graphId': typeof OrgOrgIdTeamTeamIdGraphsGraphIdRoute
  '/org/$orgId/team/$teamId/graphs/': typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/graphs/$graphId'
    | '/graphs/'
    | '/api/auth/$'
    | '/org/$orgId/'
    | '/org/$orgId/team/$teamId/graphs/$graphId'
    | '/org/$orgId/team/$teamId/graphs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/graphs/$graphId'
    | '/graphs'
    | '/api/auth/$'
    | '/org/$orgId'
    | '/org/$orgId/team/$teamId/graphs/$graphId'
    | '/org/$orgId/team/$teamId/graphs'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/graphs/$graphId'
    | '/graphs/'
    | '/api/auth/$'
    | '/org/$orgId/'
    | '/org/$orgId/team/$teamId/graphs/$graphId'
    | '/org/$orgId/team/$teamId/graphs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LoginRoute: typeof LoginRoute
  OrgsRoute: typeof OrgsRoute
  GraphsGraphIdRoute: typeof GraphsGraphIdRoute
  GraphsIndexRoute: typeof GraphsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdTeamTeamIdGraphsGraphIdRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdRoute
  OrgOrgIdTeamTeamIdGraphsIndexRoute: typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/': {
      id: '/graphs/'
      path: '/graphs'
      fullPath: '/graphs/'
      preLoaderRoute: typeof GraphsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$graphId': {
      id: '/graphs/$graphId'
      path: '/graphs/$graphId'
      fullPath: '/graphs/$graphId'
      preLoaderRoute: typeof GraphsGraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/org/$orgId'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/graphs/': {
      id: '/org/$orgId/team/$teamId/graphs/'
      path: '/org/$orgId/team/$teamId/graphs'
      fullPath: '/org/$orgId/team/$teamId/graphs/'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdGraphsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/graphs/$graphId': {
      id: '/org/$orgId/team/$teamId/graphs/$graphId'
      path: '/org/$orgId/team/$teamId/graphs/$graphId'
      fullPath: '/org/$orgId/team/$teamId/graphs/$graphId'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LoginRoute: LoginRoute,
  OrgsRoute: OrgsRoute,
  GraphsGraphIdRoute: GraphsGraphIdRoute,
  GraphsIndexRoute: GraphsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdTeamTeamIdGraphsGraphIdRoute: OrgOrgIdTeamTeamIdGraphsGraphIdRoute,
  OrgOrgIdTeamTeamIdGraphsIndexRoute: OrgOrgIdTeamTeamIdGraphsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
