/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgsRouteImport } from './routes/orgs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphsIndexRouteImport } from './routes/graphs/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known/oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as OrgOrgIdIndexRouteImport } from './routes/org/$orgId/index'
import { Route as GraphsGraphIdIndexRouteImport } from './routes/graphs/$graphId/index'
import { Route as OrgOrgIdSettingsRouteImport } from './routes/org/$orgId/settings'
import { Route as GraphsGraphIdTableRouteImport } from './routes/graphs/$graphId/table'
import { Route as GraphsGraphIdSettingsRouteImport } from './routes/graphs/$graphId/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OrgOrgIdTeamTeamIdSettingsRouteImport } from './routes/org/$orgId/team/$teamId/settings'
import { Route as OrgOrgIdTeamTeamIdGraphsIndexRouteImport } from './routes/org/$orgId/team/$teamId/graphs/index'
import { Route as OrgOrgIdTeamTeamIdGraphsGraphIdIndexRouteImport } from './routes/org/$orgId/team/$teamId/graphs/$graphId/index'
import { Route as OrgOrgIdTeamTeamIdGraphsGraphIdTableRouteImport } from './routes/org/$orgId/team/$teamId/graphs/$graphId/table'
import { Route as OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRouteImport } from './routes/org/$orgId/team/$teamId/graphs/$graphId/settings'

const OrgsRoute = OrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsIndexRoute = GraphsIndexRouteImport.update({
  id: '/graphs/',
  path: '/graphs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdIndexRoute = OrgOrgIdIndexRouteImport.update({
  id: '/org/$orgId/',
  path: '/org/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsGraphIdIndexRoute = GraphsGraphIdIndexRouteImport.update({
  id: '/graphs/$graphId/',
  path: '/graphs/$graphId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdSettingsRoute = OrgOrgIdSettingsRouteImport.update({
  id: '/org/$orgId/settings',
  path: '/org/$orgId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsGraphIdTableRoute = GraphsGraphIdTableRouteImport.update({
  id: '/graphs/$graphId/table',
  path: '/graphs/$graphId/table',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsGraphIdSettingsRoute = GraphsGraphIdSettingsRouteImport.update({
  id: '/graphs/$graphId/settings',
  path: '/graphs/$graphId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgOrgIdTeamTeamIdSettingsRoute =
  OrgOrgIdTeamTeamIdSettingsRouteImport.update({
    id: '/org/$orgId/team/$teamId/settings',
    path: '/org/$orgId/team/$teamId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdTeamTeamIdGraphsIndexRoute =
  OrgOrgIdTeamTeamIdGraphsIndexRouteImport.update({
    id: '/org/$orgId/team/$teamId/graphs/',
    path: '/org/$orgId/team/$teamId/graphs/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute =
  OrgOrgIdTeamTeamIdGraphsGraphIdIndexRouteImport.update({
    id: '/org/$orgId/team/$teamId/graphs/$graphId/',
    path: '/org/$orgId/team/$teamId/graphs/$graphId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute =
  OrgOrgIdTeamTeamIdGraphsGraphIdTableRouteImport.update({
    id: '/org/$orgId/team/$teamId/graphs/$graphId/table',
    path: '/org/$orgId/team/$teamId/graphs/$graphId/table',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute =
  OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRouteImport.update({
    id: '/org/$orgId/team/$teamId/graphs/$graphId/settings',
    path: '/org/$orgId/team/$teamId/graphs/$graphId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/graphs/': typeof GraphsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/graphs/$graphId/settings': typeof GraphsGraphIdSettingsRoute
  '/graphs/$graphId/table': typeof GraphsGraphIdTableRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRoute
  '/graphs/$graphId/': typeof GraphsGraphIdIndexRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/settings': typeof OrgOrgIdTeamTeamIdSettingsRoute
  '/org/$orgId/team/$teamId/graphs/': typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/settings': typeof OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/table': typeof OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/': typeof OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/graphs': typeof GraphsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/graphs/$graphId/settings': typeof GraphsGraphIdSettingsRoute
  '/graphs/$graphId/table': typeof GraphsGraphIdTableRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRoute
  '/graphs/$graphId': typeof GraphsGraphIdIndexRoute
  '/org/$orgId': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/settings': typeof OrgOrgIdTeamTeamIdSettingsRoute
  '/org/$orgId/team/$teamId/graphs': typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/settings': typeof OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/table': typeof OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute
  '/org/$orgId/team/$teamId/graphs/$graphId': typeof OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/login': typeof LoginRoute
  '/orgs': typeof OrgsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/api/mcp': typeof ApiMcpRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/graphs/': typeof GraphsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/graphs/$graphId/settings': typeof GraphsGraphIdSettingsRoute
  '/graphs/$graphId/table': typeof GraphsGraphIdTableRoute
  '/org/$orgId/settings': typeof OrgOrgIdSettingsRoute
  '/graphs/$graphId/': typeof GraphsGraphIdIndexRoute
  '/org/$orgId/': typeof OrgOrgIdIndexRoute
  '/org/$orgId/team/$teamId/settings': typeof OrgOrgIdTeamTeamIdSettingsRoute
  '/org/$orgId/team/$teamId/graphs/': typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/settings': typeof OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/table': typeof OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute
  '/org/$orgId/team/$teamId/graphs/$graphId/': typeof OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/oauth/consent'
    | '/graphs/'
    | '/api/auth/$'
    | '/graphs/$graphId/settings'
    | '/graphs/$graphId/table'
    | '/org/$orgId/settings'
    | '/graphs/$graphId/'
    | '/org/$orgId/'
    | '/org/$orgId/team/$teamId/settings'
    | '/org/$orgId/team/$teamId/graphs/'
    | '/org/$orgId/team/$teamId/graphs/$graphId/settings'
    | '/org/$orgId/team/$teamId/graphs/$graphId/table'
    | '/org/$orgId/team/$teamId/graphs/$graphId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/oauth/consent'
    | '/graphs'
    | '/api/auth/$'
    | '/graphs/$graphId/settings'
    | '/graphs/$graphId/table'
    | '/org/$orgId/settings'
    | '/graphs/$graphId'
    | '/org/$orgId'
    | '/org/$orgId/team/$teamId/settings'
    | '/org/$orgId/team/$teamId/graphs'
    | '/org/$orgId/team/$teamId/graphs/$graphId/settings'
    | '/org/$orgId/team/$teamId/graphs/$graphId/table'
    | '/org/$orgId/team/$teamId/graphs/$graphId'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/login'
    | '/orgs'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/api/mcp'
    | '/oauth/consent'
    | '/graphs/'
    | '/api/auth/$'
    | '/graphs/$graphId/settings'
    | '/graphs/$graphId/table'
    | '/org/$orgId/settings'
    | '/graphs/$graphId/'
    | '/org/$orgId/'
    | '/org/$orgId/team/$teamId/settings'
    | '/org/$orgId/team/$teamId/graphs/'
    | '/org/$orgId/team/$teamId/graphs/$graphId/settings'
    | '/org/$orgId/team/$teamId/graphs/$graphId/table'
    | '/org/$orgId/team/$teamId/graphs/$graphId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  LoginRoute: typeof LoginRoute
  OrgsRoute: typeof OrgsRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiMcpRoute: typeof ApiMcpRoute
  OauthConsentRoute: typeof OauthConsentRoute
  GraphsIndexRoute: typeof GraphsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  GraphsGraphIdSettingsRoute: typeof GraphsGraphIdSettingsRoute
  GraphsGraphIdTableRoute: typeof GraphsGraphIdTableRoute
  OrgOrgIdSettingsRoute: typeof OrgOrgIdSettingsRoute
  GraphsGraphIdIndexRoute: typeof GraphsGraphIdIndexRoute
  OrgOrgIdIndexRoute: typeof OrgOrgIdIndexRoute
  OrgOrgIdTeamTeamIdSettingsRoute: typeof OrgOrgIdTeamTeamIdSettingsRoute
  OrgOrgIdTeamTeamIdGraphsIndexRoute: typeof OrgOrgIdTeamTeamIdGraphsIndexRoute
  OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute
  OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute
  OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orgs': {
      id: '/orgs'
      path: '/orgs'
      fullPath: '/orgs'
      preLoaderRoute: typeof OrgsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/': {
      id: '/graphs/'
      path: '/graphs'
      fullPath: '/graphs/'
      preLoaderRoute: typeof GraphsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/': {
      id: '/org/$orgId/'
      path: '/org/$orgId'
      fullPath: '/org/$orgId/'
      preLoaderRoute: typeof OrgOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$graphId/': {
      id: '/graphs/$graphId/'
      path: '/graphs/$graphId'
      fullPath: '/graphs/$graphId/'
      preLoaderRoute: typeof GraphsGraphIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/settings': {
      id: '/org/$orgId/settings'
      path: '/org/$orgId/settings'
      fullPath: '/org/$orgId/settings'
      preLoaderRoute: typeof OrgOrgIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$graphId/table': {
      id: '/graphs/$graphId/table'
      path: '/graphs/$graphId/table'
      fullPath: '/graphs/$graphId/table'
      preLoaderRoute: typeof GraphsGraphIdTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs/$graphId/settings': {
      id: '/graphs/$graphId/settings'
      path: '/graphs/$graphId/settings'
      fullPath: '/graphs/$graphId/settings'
      preLoaderRoute: typeof GraphsGraphIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/settings': {
      id: '/org/$orgId/team/$teamId/settings'
      path: '/org/$orgId/team/$teamId/settings'
      fullPath: '/org/$orgId/team/$teamId/settings'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/graphs/': {
      id: '/org/$orgId/team/$teamId/graphs/'
      path: '/org/$orgId/team/$teamId/graphs'
      fullPath: '/org/$orgId/team/$teamId/graphs/'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdGraphsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/graphs/$graphId/': {
      id: '/org/$orgId/team/$teamId/graphs/$graphId/'
      path: '/org/$orgId/team/$teamId/graphs/$graphId'
      fullPath: '/org/$orgId/team/$teamId/graphs/$graphId/'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/graphs/$graphId/table': {
      id: '/org/$orgId/team/$teamId/graphs/$graphId/table'
      path: '/org/$orgId/team/$teamId/graphs/$graphId/table'
      fullPath: '/org/$orgId/team/$teamId/graphs/$graphId/table'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/$orgId/team/$teamId/graphs/$graphId/settings': {
      id: '/org/$orgId/team/$teamId/graphs/$graphId/settings'
      path: '/org/$orgId/team/$teamId/graphs/$graphId/settings'
      fullPath: '/org/$orgId/team/$teamId/graphs/$graphId/settings'
      preLoaderRoute: typeof OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  LoginRoute: LoginRoute,
  OrgsRoute: OrgsRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiMcpRoute: ApiMcpRoute,
  OauthConsentRoute: OauthConsentRoute,
  GraphsIndexRoute: GraphsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  GraphsGraphIdSettingsRoute: GraphsGraphIdSettingsRoute,
  GraphsGraphIdTableRoute: GraphsGraphIdTableRoute,
  OrgOrgIdSettingsRoute: OrgOrgIdSettingsRoute,
  GraphsGraphIdIndexRoute: GraphsGraphIdIndexRoute,
  OrgOrgIdIndexRoute: OrgOrgIdIndexRoute,
  OrgOrgIdTeamTeamIdSettingsRoute: OrgOrgIdTeamTeamIdSettingsRoute,
  OrgOrgIdTeamTeamIdGraphsIndexRoute: OrgOrgIdTeamTeamIdGraphsIndexRoute,
  OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute:
    OrgOrgIdTeamTeamIdGraphsGraphIdSettingsRoute,
  OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute:
    OrgOrgIdTeamTeamIdGraphsGraphIdTableRoute,
  OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute:
    OrgOrgIdTeamTeamIdGraphsGraphIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
